const {chromium}=require('/Users/joey/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');

(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:4180');
  await page.locator('.record').first().waitFor();
  await page.getByRole('button',{name:/^視覺化：/}).click();
  await page.getByRole('button',{name:'全螢幕顯示視覺化專區'}).click();await page.waitForFunction(()=>document.fullscreenElement?.id==='visualization-view');const exitFullscreen=page.getByRole('button',{name:'退出全螢幕視覺化專區'});assert.equal(await exitFullscreen.getAttribute('aria-pressed'),'true');await exitFullscreen.click();await page.waitForFunction(()=>!document.fullscreenElement);
  const barPalette=await page.locator('#viz-palette').inputValue();
  await page.getByRole('tab',{name:'泡泡圖'}).click();
  assert.notEqual(await page.locator('#viz-palette').inputValue(),barPalette);
  await page.locator('.viz-bubble-node').first().waitFor();
  const bubbleCount=await page.locator('.viz-bubble-node').count();assert(bubbleCount>0);
  assert.match(await page.locator('#viz-status').textContent(),/分析母集合 \d+ 筆/);
  assert(await page.locator('#viz-legend i').count()===6);
  for(const color of await page.locator('#viz-legend i').evaluateAll(nodes=>nodes.map(n=>getComputedStyle(n).backgroundColor)))assert.notEqual(color,'rgba(0, 0, 0, 0)');
  const originalLabelCount=await page.locator('.viz-bubble-name').count();
  const originalCountHeight=await page.locator('.viz-bubble-count').first().evaluate(n=>n.getBoundingClientRect().height);
  const positions=await page.locator('.viz-bubble-node').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('transform')));
  const bubbleLabel=await page.locator('.viz-bubble-node').first().getAttribute('aria-label');
  await page.locator('#viz-search').fill(bubbleLabel.slice(0,1));
  assert.deepEqual(await page.locator('.viz-bubble-node').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('transform'))),positions);
  await page.locator('.viz-bubble-node').first().click();assert.equal(await page.locator('.viz-bubble-node.is-selected').count(),1);
  await page.locator('#viz-zoom').fill('120');await page.waitForFunction(()=>document.querySelector('#viz-zoom-value').textContent==='120%');
  assert.equal(await page.locator('.viz-bubble-node').count(),bubbleCount);
  assert.deepEqual(await page.locator('.viz-bubble-node').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('transform'))),positions);
  const nodeBeforeZoom=await page.locator('.viz-bubble-node').first().elementHandle();
  await page.locator('#viz-zoom').fill('200');await page.waitForFunction(()=>document.querySelector('#viz-zoom-value').textContent==='200%');
  assert(await nodeBeforeZoom.evaluate(n=>n===document.querySelector('.viz-bubble-node')));
  assert(await page.locator('#viz-chart').evaluate(n=>n.scrollWidth>n.clientWidth));
  assert(await page.locator('.viz-bubble-name').count()>originalLabelCount);
  assert(await page.locator('.viz-bubble-count').first().evaluate(n=>n.getBoundingClientRect().height)>originalCountHeight);
  const beforeWheel=Number(await page.locator('#viz-zoom').inputValue()),chartBox=await page.locator('#viz-chart').boundingBox();await page.mouse.move(chartBox.x+chartBox.width/2,chartBox.y+chartBox.height/2);await page.mouse.wheel(0,180);await page.waitForFunction(value=>Number(document.querySelector('#viz-zoom').value)<value,beforeWheel);assert(Number(await page.locator('#viz-zoom').inputValue())<beforeWheel);
  const beforePan=await page.locator('#viz-chart').evaluate(n=>({left:n.scrollLeft,top:n.scrollTop})),box=await page.locator('#viz-chart').boundingBox(),selectedBeforePan=await page.locator('.viz-bubble-node.is-selected').count();
  await page.mouse.move(box.x+box.width*.7,box.y+box.height*.7);await page.mouse.down();await page.mouse.move(box.x+box.width*.45,box.y+box.height*.45,{steps:5});await page.mouse.up();
  const afterPan=await page.locator('#viz-chart').evaluate(n=>({left:n.scrollLeft,top:n.scrollTop}));assert(afterPan.left!==beforePan.left||afterPan.top!==beforePan.top);assert.equal(await page.locator('.viz-bubble-node.is-selected').count(),selectedBeforePan);
  await page.locator('#viz-sort').selectOption('title-asc');assert(await page.locator('#viz-chart').evaluate(n=>n.classList.contains('viz-layout-enter')));
  await page.locator('#viz-palette').selectOption('moss');
  assert.equal(await page.locator('#viz-legend i').last().evaluate(n=>getComputedStyle(n).backgroundColor),await page.locator('.bubble-level-5:not(.is-selected) circle').first().evaluate(n=>getComputedStyle(n).fill));
  await page.locator('#viz-clear-search').click();
  await page.getByRole('tab',{name:'資料表格'}).click();
  await page.locator('.viz-data-table tbody tr').first().waitFor();
  const tableZoomBefore=Number(await page.locator('#viz-zoom').inputValue()),tableBox=await page.locator('#viz-chart').boundingBox();await page.mouse.move(tableBox.x+tableBox.width/2,tableBox.y+tableBox.height/2);await page.mouse.wheel(0,-140);await page.waitForFunction(value=>Number(document.querySelector('#viz-zoom').value)>value,tableZoomBefore);
  const tableScrollBefore=await page.locator('#viz-chart').evaluate(n=>n.scrollTop);await page.locator('#viz-zoom').fill('200');await page.mouse.move(tableBox.x+tableBox.width*.7,tableBox.y+tableBox.height*.7);await page.mouse.down();await page.mouse.move(tableBox.x+tableBox.width*.7,tableBox.y+tableBox.height*.4,{steps:5});await page.mouse.up();assert.notEqual(await page.locator('#viz-chart').evaluate(n=>n.scrollTop),tableScrollBefore);
  assert.equal(await page.locator('.viz-data-table thead th').allTextContents().then(x=>x.join('|')),'序號|類別名稱|文件數|比例|累積比例');
  const rows=await page.locator('.viz-data-table tbody tr').count();assert(rows>0);
  const percentages=await page.locator('.viz-data-table tbody tr').first().locator('td').nth(3).textContent();assert.match(percentages,/%/);
  const firstLabel=await page.locator('.viz-table-label').first().textContent();await page.locator('#viz-search').fill(firstLabel.slice(0,1));assert(await page.locator('.viz-data-table tbody tr.is-unmatched').count()<rows);
  await page.locator('#viz-search').fill('不存在的項目');
  assert.equal(await page.locator('.viz-data-table tbody tr').count(),rows);
  assert.equal(await page.locator('.viz-data-table tbody tr.is-unmatched').count(),rows);
  assert.equal(await page.locator('.viz-data-table tbody tr.is-selected').count(),1);
  await page.locator('.viz-data-table tbody tr.is-selected').click();
  assert.equal(await page.locator('.viz-data-table tbody tr.is-selected').count(),0);
  await page.locator('#viz-zoom').fill('70');assert.equal(await page.locator('#viz-zoom-value').textContent(),'70%');
  const downloadPromise=page.waitForEvent('download');await page.locator('#viz-export').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/\.csv$/);
  await page.getByRole('tab',{name:'長條圖'}).click();assert(await page.locator('.viz-bar-row').count()===rows);const barZoomBefore=Number(await page.locator('#viz-zoom').inputValue()),barBox=await page.locator('#viz-chart').boundingBox();await page.mouse.move(barBox.x+barBox.width/2,barBox.y+barBox.height/2);await page.mouse.wheel(0,-140);await page.waitForFunction(value=>Number(document.querySelector('#viz-zoom').value)>value,barZoomBefore);
  assert.deepEqual(errors,[]);
  console.log('Visualization table flows passed; rows:',rows);
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exit(1)});
