import {VisualizationState,prepareItems,prepareTableRows,tableCSV,tableRowHeight,tableFontSize,zoomRowHeight,zoomLabelSize,normalizeSearch,formatPercent} from './core/visualization.js';
import {packBubbles,bubbleLevel,bubbleLabel} from './core/bubble.js';

const $=s=>document.querySelector(s);
const make=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node};
const svgMake=(tag,cls)=>{const node=document.createElementNS('http://www.w3.org/2000/svg',tag);if(cls)node.setAttribute('class',cls);return node};
function markedLabel(text,query,cls='viz-label'){const span=make('span',undefined,cls),term=normalizeSearch(query),source=normalizeSearch(text),at=term?source.indexOf(term):-1;if(at<0){span.textContent=text;return span}span.append(document.createTextNode(text.slice(0,at)),make('mark',text.slice(at,at+query.length)),document.createTextNode(text.slice(at+query.length)));return span}
function safeName(value){return String(value||'資料表格').replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'資料表格'}

export class Visualization{
 constructor({getContext,onClose}){
  this.getContext=getContext;this.onClose=onClose;this.state=new VisualizationState();this.context=null;this.pushed=false;
  this.view=$('#visualization-view');this.analysis=$('#analysis-view');this.chart=$('#viz-chart');this.tabs=[...document.querySelectorAll('.viz-tabs [data-view]')];
  $('#viz-back').onclick=()=>this.close();$('#viz-search').oninput=e=>{this.state.search=e.target.value;this.render('search')};$('#viz-clear-search').onclick=()=>{this.state.search='';$('#viz-search').value='';this.render('search');$('#viz-search').focus()};$('#viz-sort').onchange=e=>{this.state.sort=e.target.value;this.render('sort')};$('#viz-palette').onchange=e=>{this.state.palette=e.target.value;this.render('palette')};$('#viz-zoom').oninput=e=>{this.state.zoom[this.state.view]=Number(e.target.value);if(this.state.view==='bubble'){cancelAnimationFrame(this.bubbleFrame);this.bubbleFrame=requestAnimationFrame(()=>this.render('zoom'))}else this.applyZoom()};$('#viz-export').onclick=()=>this.exportCSV();$('#viz-fullscreen').onclick=()=>this.toggleFullscreen();
  for(const tab of this.tabs){tab.onclick=()=>this.selectView(tab.dataset.view);tab.onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const offset=e.key==='ArrowRight'?1:-1,index=this.tabs.indexOf(tab),next=this.tabs[(index+offset+this.tabs.length)%this.tabs.length];this.selectView(next.dataset.view);next.focus()}}
  this.labelResizeObserver=new ResizeObserver(()=>{if(this.opened&&this.state.view==='bubble'){if(this.bubbleContainerWidth===this.chart.offsetWidth)return;cancelAnimationFrame(this.bubbleResizeFrame);this.bubbleResizeFrame=requestAnimationFrame(()=>this.render('resize'))}else this.fitLabels()});this.labelResizeObserver.observe(this.chart);
  this.chart.onpointerdown=e=>this.startBubblePan(e);this.chart.onpointermove=e=>this.moveBubblePan(e);this.chart.onpointerup=e=>this.endBubblePan(e);this.chart.onpointercancel=e=>this.endBubblePan(e);
  this.chart.onwheel=e=>this.wheelVisualizationZoom(e);
  document.addEventListener('fullscreenchange',()=>this.updateFullscreenButton());
  addEventListener('popstate',()=>{if(this.opened&&!location.hash.includes('visualization'))this.close(false)});
 }
 open(){
  this.context=this.getContext();this.state.setSource(this.context.key,this.context.sort);this.state.ensurePalette();this.opened=true;this.analysis.hidden=true;this.view.hidden=false;$('#viz-source').replaceChildren(make('span','分析標的','viz-source-label'),make('strong',`${this.context.type}：${this.context.name}`));$('#viz-search').value=this.state.search;$('#viz-sort').value=this.state.sort;$('#viz-palette').value=this.state.palette;this.updateTabs();if(!location.hash.includes('visualization')){history.pushState({view:'visualization'},'',location.pathname+location.search+'#visualization');this.pushed=true}this.render('open');this.chart.scrollTop=0;$('#viz-back').focus();
 }
 close(navigate=true){if(!this.opened)return;if(document.fullscreenElement===this.view)document.exitFullscreen();this.opened=false;this.view.hidden=true;this.analysis.hidden=false;if(navigate&&this.pushed&&location.hash.includes('visualization')){this.pushed=false;history.back()}else if(navigate&&location.hash.includes('visualization'))history.replaceState({},'',location.pathname+location.search);this.onClose?.()}
 selectView(view){if(!['bar','bubble','table'].includes(view)||view===this.state.view)return;this.state.view=view;this.state.ensurePalette();this.updateTabs();this.render('view');this.chart.scrollTop=0;this.chart.scrollLeft=0}
 updateTabs(){for(const tab of this.tabs){const selected=tab.dataset.view===this.state.view;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1}$('#viz-export').hidden=this.state.view!=='table';$('#viz-legend').hidden=this.state.view!=='bubble';$('#viz-zoom').value=String(this.state.zoom[this.state.view]);$('#viz-palette').value=this.state.palette;this.chart.classList.toggle('is-table',this.state.view==='table');this.chart.classList.toggle('is-bubble',this.state.view==='bubble')}
 applyZoom(anchor){if(this.state.view==='table')this.applyTableZoom(anchor);else if(this.state.view==='bubble')this.applyBubbleZoom(anchor);else {this.applyBarZoom(anchor);this.fitLabels()}}
 applyBubbleZoom(anchor){
  $('#viz-zoom-value').value=this.state.zoom.bubble+'%';const svg=this.chart.querySelector('.viz-bubble-svg');if(!svg)return;
  const old=Number(svg.dataset.zoom)||1,z=this.state.zoom.bubble/100,box=svg.viewBox.baseVal,focus=svg.contains(document.activeElement)?document.activeElement:null;
  const rect=focus?.getBoundingClientRect(),chartRect=this.chart.getBoundingClientRect(),anchorX=anchor?.x??(rect?rect.left+rect.width/2-chartRect.left:this.chart.clientWidth/2),anchorY=anchor?.y??(rect?rect.top+rect.height/2-chartRect.top:this.chart.clientHeight/2);
  const offset=svg.getBoundingClientRect().left-chartRect.left+this.chart.scrollLeft,x=(this.chart.scrollLeft+anchorX-offset)/old,y=(this.chart.scrollTop+anchorY-8)/old;
  svg.setAttribute('width',String(box.width*z));svg.setAttribute('height',String(box.height*z));svg.dataset.zoom=String(z);
  this.updateBubbleLabels(svg,z);
  if(old!==z){const nextOffset=svg.getBoundingClientRect().left-chartRect.left+this.chart.scrollLeft;this.chart.scrollLeft=Math.max(0,nextOffset+x*z-anchorX);this.chart.scrollTop=Math.max(0,8+y*z-anchorY)}
 }
 updateBubbleLabels(svg,z=1){
  for(const group of svg.querySelectorAll('.viz-bubble-node')){
   group.querySelectorAll('.viz-bubble-name,.viz-bubble-count').forEach(node=>node.remove());
   const radius=Number(group.dataset.radius),detail=bubbleLabel(group.dataset.label,radius*z,Math.sqrt(z)),unit=1/z;
   if(detail.lines.length){const name=svgMake('text','viz-bubble-name');name.setAttribute('text-anchor','middle');name.setAttribute('font-size',String(detail.size*unit));detail.lines.forEach((line,i)=>{const part=svgMake('tspan');part.setAttribute('x','0');part.setAttribute('y',String((detail.startY+i*detail.lineHeight)*unit));part.textContent=line;name.append(part)});group.append(name)}
   if(radius*z>=19){const count=svgMake('text','viz-bubble-count');count.setAttribute('text-anchor','middle');count.setAttribute('y',String((detail.lines.length?detail.countY:detail.countSize*.34)*unit));count.setAttribute('font-size',String(detail.countSize*unit));count.textContent=group.dataset.count;group.append(count)}
  }
 }
 wheelVisualizationZoom(event){if(event.ctrlKey)return;event.preventDefault();const current=this.state.zoom[this.state.view],next=Math.max(10,Math.min(200,Math.round(current*Math.exp(-event.deltaY*.0015))));if(next===current)return;const rect=this.chart.getBoundingClientRect(),anchor={x:event.clientX-rect.left,y:event.clientY-rect.top};this.state.zoom[this.state.view]=next;$('#viz-zoom').value=String(next);cancelAnimationFrame(this.wheelZoomFrame);this.wheelZoomFrame=requestAnimationFrame(()=>this.applyZoom(anchor))}
 startBubblePan(event){if(event.button!==0)return;this.bubblePan={id:event.pointerId,x:event.clientX,y:event.clientY,left:this.chart.scrollLeft,top:this.chart.scrollTop};this.bubbleDragged=false}
 moveBubblePan(event){if(!this.bubblePan||event.pointerId!==this.bubblePan.id)return;const dx=event.clientX-this.bubblePan.x,dy=event.clientY-this.bubblePan.y;if(!this.bubbleDragged&&Math.hypot(dx,dy)>4){this.bubbleDragged=true;this.chart.setPointerCapture(event.pointerId);this.chart.classList.add('is-panning')}if(!this.bubbleDragged)return;this.chart.scrollLeft=this.bubblePan.left-dx;this.chart.scrollTop=this.bubblePan.top-dy;event.preventDefault()}
 endBubblePan(event){if(!this.bubblePan||event.pointerId!==this.bubblePan.id)return;this.chart.releasePointerCapture?.(event.pointerId);this.bubblePan=null;this.chart.classList.remove('is-panning');if(this.bubbleDragged)setTimeout(()=>{this.bubbleDragged=false},0)}
 animateLayout(reason){if(!['open','view','sort','resize'].includes(reason)||matchMedia('(prefers-reduced-motion: reduce)').matches)return;this.chart.classList.remove('viz-layout-enter');void this.chart.offsetWidth;this.chart.classList.add('viz-layout-enter');clearTimeout(this.layoutTimer);this.layoutTimer=setTimeout(()=>this.chart.classList.remove('viz-layout-enter'),480)}
 fitLabels(){cancelAnimationFrame(this.labelFrame);this.labelFrame=requestAnimationFrame(()=>{if(!this.opened||this.state.view!=='bar')return;const labels=[...this.chart.querySelectorAll('.viz-label')];for(const label of labels)label.classList.remove('is-wrapped');if(this.state.zoom.bar<40)return;const size=Math.max(12,Math.min(zoomLabelSize(this.state.zoom.bar)*.85,(zoomRowHeight(this.state.zoom.bar)-4)/2.3));this.chart.style.setProperty('--viz-wrapped-size',size+'px');const overflowing=labels.filter(label=>label.scrollWidth>label.clientWidth+1);for(const label of overflowing){label.classList.add('is-wrapped');label.title=label.textContent}})}
 applyBarZoom(anchor){const oldHeight=Number.parseFloat(getComputedStyle(this.chart).getPropertyValue('--viz-row-height'))||48,anchorY=anchor?.y??this.chart.clientHeight/2,center=(this.chart.scrollTop+anchorY)/oldHeight,height=zoomRowHeight(this.state.zoom.bar);this.chart.style.setProperty('--viz-row-height',height+'px');this.chart.style.setProperty('--viz-label-size',zoomLabelSize(this.state.zoom.bar)+'px');this.chart.classList.toggle('viz-dense',this.state.zoom.bar<40);$('#viz-zoom-value').value=this.state.zoom.bar+'%';this.chart.scrollTop=Math.max(0,center*height-anchorY)}
 applyTableZoom(anchor){const oldHeight=Number.parseFloat(getComputedStyle(this.chart).getPropertyValue('--viz-table-row-height'))||51,anchorY=anchor?.y??this.chart.clientHeight/2,center=(this.chart.scrollTop+anchorY)/oldHeight,height=tableRowHeight(this.state.zoom.table);this.chart.style.setProperty('--viz-table-row-height',height+'px');this.chart.style.setProperty('--viz-table-font-size',tableFontSize(this.state.zoom.table)+'px');$('#viz-zoom-value').value=this.state.zoom.table+'%';this.chart.scrollTop=Math.max(0,center*height-anchorY)}
 async toggleFullscreen(){if(document.fullscreenElement===this.view)await document.exitFullscreen();else if(this.view.requestFullscreen)await this.view.requestFullscreen();this.updateFullscreenButton()}
 updateFullscreenButton(){const active=document.fullscreenElement===this.view,button=$('#viz-fullscreen');button.setAttribute('aria-label',active?'退出全螢幕視覺化專區':'全螢幕顯示視覺化專區');button.title=active?'退出全螢幕':'全螢幕顯示';button.setAttribute('aria-pressed',String(active))}
 render(reason){
  if(reason==='zoom'&&this.state.view==='bubble'){this.applyBubbleZoom();return}
  const items=prepareItems(this.context.items,this.state.search,this.state.sort),matches=items.filter(x=>x.matched);this.chart.dataset.palette=this.state.palette;this.chart.classList.toggle('has-search',Boolean(this.state.search));$('#viz-clear-search').disabled=!this.state.search;$('#viz-status').textContent=this.state.view==='table'?`符合 ${matches.length}／全部 ${items.length} 項 · 分析母集合 ${this.context.documentTotal} 筆 · 各類別可能包含相同文件，累積比例可能超過 100%`:this.state.view==='bubble'?`符合 ${matches.length}／全部 ${items.length} 項 · 文件數 · 分析母集合 ${this.context.documentTotal} 筆`:`符合 ${matches.length}／全部 ${items.length} 項 · 文件數`;
  this.selection(items);this.chart.replaceChildren();this.updateTabs();
  if(!items.length){this.chart.append(make('p','此條件下沒有可視覺化項目','viz-empty'));return}
  if(this.state.view==='table')this.renderTable(items);else if(this.state.view==='bubble')this.renderBubbles(items);else this.renderBars(items);
  this.applyZoom();
  this.animateLayout(reason);
  if(reason==='search'&&matches.length)this.chart.querySelector(`[data-value=${CSS.escape(matches[0].value)}]`)?.scrollIntoView({block:'nearest'});
 }
 renderBars(items){
  const max=Math.max(1,...items.map(x=>x.count)),top=new Set(prepareItems(this.context.items,'','count-desc').slice(0,3).map(x=>x.value));
  for(const item of items){const row=make('button',undefined,'viz-bar-row');row.type='button';this.decorateRow(row,item,top);const track=make('span',undefined,'viz-bar-track'),bar=make('span',undefined,'viz-bar'),count=make('span',String(item.count),'viz-count');bar.style.width=`calc((100% - 54px) * ${item.count/max})`;bar.title=`${item.label}：${item.count}筆`;bar.setAttribute('aria-label',bar.title);track.append(bar,count);row.append(markedLabel(item.label,item.matched?this.state.search:''),track);this.bindSelection(row,item);this.chart.append(row)}
  this.chart.setAttribute('aria-label',`${this.context.type}${this.context.name}水平長條圖，符合${items.filter(x=>x.matched).length}項，共${items.length}項`)
 }
 renderTable(items){
  const rows=prepareTableRows(items,this.context.documentTotal),top=new Set(prepareItems(this.context.items,'','count-desc').slice(0,3).map(x=>x.value)),table=make('table',undefined,'viz-data-table'),caption=make('caption',`${this.context.type}：${this.context.name}；分析母集 ${this.context.documentTotal} 筆文件`),head=make('thead'),headRow=make('tr'),body=make('tbody');
  for(const title of ['序號','類別名稱','文件數','比例','累積比例']){const th=make('th',title);th.scope='col';headRow.append(th)}head.append(headRow);
  for(const item of rows){const row=make('tr');row.tabIndex=0;row.setAttribute('role','button');this.decorateRow(row,item,top);const ratio=make('div',undefined,'viz-ratio'),meter=make('span',undefined,'viz-ratio-track'),fill=make('span',undefined,'viz-ratio-fill');fill.style.width=`${Math.max(0,Math.min(100,item.proportion||0))}%`;meter.append(fill);ratio.append(meter,make('span',formatPercent(item.proportion)));const name=make('td');name.append(markedLabel(item.label,item.matched?this.state.search:'','viz-table-label'));for(const cell of [make('td',String(item.rank)),name,make('td',String(item.count)),make('td'),make('td',formatPercent(item.cumulative))])row.append(cell);row.children[3].append(ratio);this.bindSelection(row,item);body.append(row)}
  table.append(caption,head,body);this.chart.append(table);this.chart.setAttribute('aria-label',`${this.context.type}${this.context.name}資料表格，符合${items.filter(x=>x.matched).length}項，共${items.length}項，分析母集${this.context.documentTotal}筆文件`)
 }
 renderBubbles(items){
  this.bubbleContainerWidth=this.chart.offsetWidth;
  const width=Math.max(320,this.bubbleContainerWidth-24),layout=packBubbles(items,width,100,8),positive=layout.nodes,min=positive.length?Math.min(...positive.map(x=>x.count)):0,max=positive.length?Math.max(...positive.map(x=>x.count)):0,stage=make('div',undefined,'viz-bubble-stage'),svg=svgMake('svg','viz-bubble-svg');
  svg.setAttribute('viewBox',`0 0 ${layout.width} ${layout.height}`);svg.setAttribute('width',String(layout.width));svg.setAttribute('height',String(layout.height));svg.setAttribute('role','group');svg.setAttribute('aria-label',`${this.context.name}泡泡圖`);
  positive.forEach((item,index)=>{const group=svgMake('g',`viz-bubble-node bubble-level-${bubbleLevel(item.count,min,max)}`);group.setAttribute('transform',`translate(${item.x} ${item.y})`);group.tabIndex=0;group.dataset.bubbleIndex=String(index);group.dataset.label=item.label;group.dataset.count=String(item.count);group.dataset.radius=String(item.r);this.decorateRow(group,item,new Set());const circle=svgMake('circle','viz-bubble-circle');circle.setAttribute('r',String(item.r));const title=svgMake('title');title.textContent=`${item.label}：${item.count}筆`;group.append(title,circle);this.bindSelection(group,item);svg.append(group)});
  this.updateBubbleLabels(svg,1);
  stage.append(svg);if(layout.zeros.length){const zeros=make('div',undefined,'viz-bubble-zeros');zeros.append(make('strong','0筆項目：'));for(const item of layout.zeros){const button=make('button',`${item.label}：0筆`);button.type='button';this.decorateRow(button,item,new Set());this.bindSelection(button,item);zeros.append(button)}stage.append(zeros)}this.chart.append(stage);this.renderBubbleLegend(positive,min,max);this.chart.setAttribute('aria-label',`${this.context.type}${this.context.name}泡泡圖，符合${items.filter(x=>x.matched).length}項，共${items.length}項，分析母集合${this.context.documentTotal}筆文件`)
 }
 renderBubbleLegend(items,min,max){const legend=$('#viz-legend');legend.replaceChildren();if(!items.length){legend.hidden=true;return}legend.hidden=false;const colors=getComputedStyle(this.chart);for(let i=1;i<=6;i++)legend.style.setProperty(`--bubble-${i}`,colors.getPropertyValue(`--bubble-${i}`));legend.append(make('span','面積與色深代表文件數'),make('span',String(min),'viz-legend-value'));for(let i=0;i<6;i++)legend.append(make('i',undefined,`bubble-level-${i}`));legend.append(make('span',String(max),'viz-legend-value'))}
 decorateRow(row,item,top){row.dataset.value=item.value;row.classList.toggle('is-top-three',top.has(item.value));row.classList.toggle('is-unmatched',!item.matched);row.classList.toggle('is-selected',this.state.selected.has(item.value));row.setAttribute('aria-pressed',String(this.state.selected.has(item.value)));row.setAttribute('aria-label',`${item.label}，${item.count}筆${item.matched?'，符合搜尋':'，不符合搜尋'}${this.state.selected.has(item.value)?'，已標示':''}`)}
 bindSelection(row,item){row.onclick=()=>{if(this.bubbleDragged){this.bubbleDragged=false;return}this.state.toggle(item.value);this.render('selection')};row.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();row.click();return}if(row.classList.contains('viz-bubble-node')&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const nodes=[...this.chart.querySelectorAll('.viz-bubble-node')],at=nodes.indexOf(row),step=['ArrowLeft','ArrowUp'].includes(e.key)?-1:1;nodes[(at+step+nodes.length)%nodes.length]?.focus()}};row.onfocus=()=>{$('#viz-focus-detail').textContent=`${item.label} · ${item.count}筆${this.state.selected.has(item.value)?' · 已標示':''}`}}
 selection(items){const box=$('#viz-selection');box.replaceChildren();box.hidden=!this.state.selected.size;if(box.hidden)return;const names=new Map(items.map(x=>[x.value,x.label]));for(const value of this.state.selected){const b=make('button',(names.get(value)||value)+' ×');b.type='button';b.onclick=()=>{this.state.toggle(value);this.render('selection')};box.append(b)}const clear=make('button',`清除 ${this.state.selected.size} 項`,'viz-clear-selection');clear.type='button';clear.onclick=()=>{this.state.clearSelection();this.render('selection')};box.append(clear)}
 exportCSV(){const items=prepareItems(this.context.items,this.state.search,this.state.sort),rows=prepareTableRows(items,this.context.documentTotal),blob=new Blob([tableCSV(rows)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=make('a');link.href=url;link.download=`${safeName(this.context.name)}-${safeName(this.context.version)}.csv`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
}
